spring:
  application:
    name: zuul-service
server:
  port: 6069
  tomcat:
      #context-path: /xycar
      #access-log-enabled: true
      #basedir: ${logging.path}
      uri-encoding: UTF-8
      connection-timeout: 5000
      acceptCount: 100
      threads:
        max: 200
eureka:
  client:
    healthcheck:
      enabled: true
    service-url:
      #defaultZone: http://192.168.177.142:8080/eureka/eureka,http://192.168.177.143:8080/eureka/eureka,
      defaultZone: http://127.0.0.1:7000/eureka
    registry-fetch-interval-seconds: 30
  instance:
    instance-id:  ${spring.application.name}:${spring.cloud.client.ip-address}:${spring.application.instance_id:${server.port}}
    prefer-ip-address: true
    lease-expiration-duration-in-seconds: 90
    leaseRenewalIntervalInSeconds: 30

#路由配置
zuul:
  host:
    connect-timeout-millis: 60000
    socket-timeout-millis: 60000
  routes:
    zuul-server01:
        path: /api-a/**
        #地址方式
        #url: http://192.168.177.142:8080
        #服务方式
        serviceId: qiancheng-customer
    zuul-server02:
        path: /api-b/**
        #url: http://192.168.177.142:8080
        #服务方式
        serviceId: qiancheng-producer
  prefix: /api
  #重试
  retryable: true
zuul-server01:
  rabbion:
    listOfServers: http://192.168.177.142:8080,http://192.168.177.143:8080
zuul-server02:
  rabbion:
    listOfServers: http://192.168.177.142:8080,http://192.168.177.143:8080

#熔断机制
hystrix:
  command:
    default:
      execution:
        isolation:
          thread:
            timeoutInMilliseconds: 6000


#负载均衡
ribbon:
  ConnectionTimeout: 500 #请求连接的超时时间（ms）。
  ReadTimeout: 2000 #请求处理的超时时间（ms）。
  maxAutoRetries: 1 #对当前实例的重试次数。
  maxAutoRetriesNextServer: 3 #切换实例的最大重试次数。
  okToRetryOnAllOperations: true #对所有操作请求都进行重试
  retryableStatusCodes: 500,404,502 #对指定的 Http 响应码进行重试。



  ## 配置不被zuul管理的服务列表。多个服务名称使用逗号','分隔。
  # 配置的服务将不被zuul代理,*代表全部服务
  #ignored-services: a,b,c
  #ignored-services: *
  #过滤掉path包含admin的请求
  #ignoredPatterns: /**/admin/**

